name: my_zhipin_boss

description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.5.0
  oktoast: ^2.1.9
  fluro: ^1.5.0
  url_launcher: ^5.0.3
  dio: ^1.0.17
  flutter_slidable: ^0.5.3
  sticky_header_list: ^1.0.6
  cached_network_image: ^2.2.0+1
  #image_picker: ^0.6.0+10
  keyboard_actions: ^2.1.1+1
  shared_preferences: ^0.5.6
  webview_flutter: ^0.3.9+1
  emoji_picker: ^0.0.2
  json_model: ^0.0.2
  build_runner: ^1.6.7
  json_serializable: ^2.0.0
  json_annotation: ^2.2.0
  cloud_firestore: ^0.12.9+1
  scoped_model: ^1.0.1
  font_awesome_flutter: ^8.0.1
  flutter_swiper: ^1.1.6
  pin_view: ^1.0.1
  firebase_auth: ^0.14.0+5
  device_info: ^0.4.2+4
  connectivity: ^0.4.9
#  flutter_cupertino_date_picker: ^1.0.12
  intl: ^0.16.1
  http: ^0.12.2
  sticky_headers: "^0.1.8"
  scrollable_positioned_list: ^0.1.9
  image_picker: ^0.6.7+22
  uuid: ^2.2.2
  flutter_svg: ^0.17.4
  fluttertoast: ^7.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
    


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/tabbar/
     - assets/images/tutorial/
     - assets/images/icon/
     - assets/images/
     - assets/images/avatars/
     - assets/login_logo.png
     - assets/images/login/
     - assets/json/fieldareas.json
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PingFang
      fonts:
        - asset: assets/fonts/pf.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages